import {
  Battery,
  BatteryCharging,
  Boxes,
  Cable,
  CircuitBoard,
  Cloud,
  Container,
  Cpu,
  Database,
  Fan,
  Gamepad2,
  Globe,
  HardDrive,
  Laptop,
  Layers,
  Lightbulb,
  LockKeyhole,
  MemoryStick,
  Microchip,
  Monitor,
  MonitorCog,
  Network,
  PanelTop,
  Plug,
  Printer,
  Radio,
  Router,
  Rows3,
  Server,
  Shield,
  ShieldCheck,
  Smartphone,
  Square,
  SquareDashed,
  Tablet,
  Tv,
  Waypoints,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { ComponentKind, DeviceKind } from '@/models'

export const DEVICE_ICONS: Record<DeviceKind, LucideIcon> = {
  router: Router,
  firewall: Shield,
  switch: Network,
  'managed-switch': Network,
  'poe-switch': Zap,
  'access-point': Wifi,
  modem: Radio,
  gateway: Router,
  'vpn-gateway': LockKeyhole,
  server: Server,
  nas: Database,
  storage: HardDrive,
  'raspberry-pi': Microchip,
  'mini-pc': MonitorCog,
  workstation: Monitor,
  pc: Monitor,
  laptop: Laptop,
  phone: Smartphone,
  tablet: Tablet,
  tv: Tv,
  console: Gamepad2,
  iot: Lightbulb,
  printer: Printer,
  dns: Globe,
  dhcp: Waypoints,
  'reverse-proxy': Workflow,
  vpn: ShieldCheck,
  docker: Container,
  vm: Layers,
  kubernetes: Boxes,
  app: Square,
  cloud: Cloud,
  internet: Globe,
  'patch-panel': Rows3,
  pdu: Plug,
  ups: BatteryCharging,
  shelf: PanelTop,
  'cable-management': Cable,
  'blank-panel': SquareDashed,
}

export const COMPONENT_ICONS: Record<ComponentKind, LucideIcon> = {
  mainboard: CircuitBoard,
  cpu: Cpu,
  ram: MemoryStick,
  storage: HardDrive,
  nic: Network,
  psu: Zap,
  fan: Fan,
  gpu: Microchip,
  hba: Cable,
  raid: Database,
  pcie: CircuitBoard,
  bbu: Battery,
  custom: Square,
}

export function DeviceIcon({ kind, className }: { kind: DeviceKind; className?: string }) {
  const I = DEVICE_ICONS[kind] ?? Square
  return <I className={className} />
}

export function ComponentIcon({ kind, className }: { kind: ComponentKind; className?: string }) {
  const I = COMPONENT_ICONS[kind] ?? Square
  return <I className={className} />
}

export const COMPONENT_KIND_LABELS: Record<ComponentKind, string> = {
  mainboard: 'Mainboard',
  cpu: 'CPU',
  ram: 'RAM',
  storage: 'Laufwerk',
  nic: 'Netzwerkkarte',
  psu: 'Netzteil',
  fan: 'Lüfter',
  gpu: 'GPU',
  hba: 'HBA',
  raid: 'RAID-Controller',
  pcie: 'PCIe-Karte',
  bbu: 'Cache-Schutz',
  custom: 'Eigene Komponente',
}
